/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wind_ndk_audio_player_AudioTrackPlayer */

#ifndef _Included_com_wind_ndk_audio_player_AudioTrackPlayer
#define _Included_com_wind_ndk_audio_player_AudioTrackPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wind_ndk_audio_player_AudioTrackPlayer
 * Method:    nativeReadSamples
 * Signature: (J[SI)I
 */
JNIEXPORT jint JNICALL Java_com_wind_ndk_audio_player_AudioTrackPlayer_nativeReadSamples
  (JNIEnv *, jobject, jlong, jshortArray, jint);

/*
 * Class:     com_wind_ndk_audio_player_AudioTrackPlayer
 * Method:    nativeInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wind_ndk_audio_player_AudioTrackPlayer_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_wind_ndk_audio_player_AudioTrackPlayer
 * Method:    nativeSetDataSource
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wind_ndk_audio_player_AudioTrackPlayer_nativeSetDataSource
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_wind_ndk_audio_player_AudioTrackPlayer
 * Method:    nativePrepare
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_wind_ndk_audio_player_AudioTrackPlayer_nativePrepare
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wind_ndk_audio_player_AudioTrackPlayer
 * Method:    nativeStart
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_wind_ndk_audio_player_AudioTrackPlayer_nativeStart
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wind_ndk_audio_player_AudioTrackPlayer
 * Method:    nativePause
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_wind_ndk_audio_player_AudioTrackPlayer_nativePause
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wind_ndk_audio_player_AudioTrackPlayer
 * Method:    nativeStop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_wind_ndk_audio_player_AudioTrackPlayer_nativeStop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wind_ndk_audio_player_AudioTrackPlayer
 * Method:    nativeRelease
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_wind_ndk_audio_player_AudioTrackPlayer_nativeRelease
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wind_ndk_audio_player_AudioTrackPlayer
 * Method:    nativeGetMetadata
 * Signature: (J)Lcom/wind/ndk/audio/player/Metadata;
 */
JNIEXPORT jobject JNICALL Java_com_wind_ndk_audio_player_AudioTrackPlayer_nativeGetMetadata
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wind_ndk_audio_player_AudioTrackPlayer
 * Method:    nativeGetMinBufferSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_wind_ndk_audio_player_AudioTrackPlayer_nativeGetMinBufferSize
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
